# Generated by Django 4.0.4 on 2022-07-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('type_identification_document', models.CharField(default='cedula', max_length=10)),
                ('fisrt_name', models.CharField(max_length=25)),
                ('second_name', models.CharField(blank=True, max_length=25)),
                ('father_surname', models.CharField(max_length=25)),
                ('mother_surname', models.CharField(blank=True, max_length=25)),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_technical', to='procedure.generalprocedure')),
            ],
            options={
                'verbose_name': 'Responsible Data',
                'verbose_name_plural': 'Responsibles Data',
            },
        ),
    ]
