# Generated by Django 4.0.4 on 2022-06-04 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('type_identification_document', models.CharField(max_length=10)),
                ('fisrt_name', models.CharField(max_length=25)),
                ('second_name', models.CharField(blank=True, max_length=25)),
                ('father_surname', models.CharField(max_length=25)),
                ('mother_surname', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name': 'Documento de Identificacion',
                'verbose_name_plural': 'Documentos de Identificacion',
            },
        ),
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, default='Ecuador', max_length=50)),
                ('province', models.CharField(default='Guayas', max_length=50)),
                ('town', models.CharField(blank=True, default='Guayaquil', max_length=50)),
                ('parish', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('main_road_name', models.CharField(max_length=100)),
                ('cross_road_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('identification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientData.identificationdocument')),
            ],
            options={
                'verbose_name': 'Datos del cliente',
                'verbose_name_plural': 'Datos de los clientes',
            },
        ),
    ]
