# Generated by Django 4.0.4 on 2023-02-25 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastralModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=3)),
                ('apple', models.CharField(max_length=4)),
                ('lot', models.CharField(max_length=3)),
                ('div1', models.CharField(blank=True, default='0', max_length=1)),
                ('div2', models.CharField(blank=True, default='0', max_length=1)),
                ('div3', models.CharField(blank=True, default='0', max_length=1)),
                ('div4', models.CharField(blank=True, default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catastro de la casa',
                'verbose_name_plural': 'Catastro de las casas',
            },
        ),
        migrations.CreateModel(
            name='HouseClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, default='Ecuador', max_length=50)),
                ('province', models.CharField(default='Guayas', max_length=50)),
                ('town', models.CharField(blank=True, default='Guayaquil', max_length=50)),
                ('parish', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('main_road_name', models.CharField(max_length=100)),
                ('cross_road_name', models.CharField(blank=True, max_length=100)),
                ('coordinates', models.URLField(blank=True, max_length=500)),
                ('conventional', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_cadastral_data', models.OneToOneField(db_column='id_cadastral_data', on_delete=django.db.models.deletion.CASCADE, related_name='cadastral_data', to='clientData.cadastralmodel')),
            ],
            options={
                'verbose_name': 'Casa del cliente',
                'verbose_name_plural': 'Casas de los clientes',
            },
        ),
        migrations.CreateModel(
            name='MunicipalAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial municipal',
                'verbose_name_plural': 'Credenciales municipales',
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=13, unique=True)),
                ('type_identification_document', models.CharField(default='cedula', max_length=10)),
                ('fisrt_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(blank=True, max_length=30)),
                ('father_surname', models.CharField(max_length=30)),
                ('mother_surname', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos de la persona',
                'verbose_name_plural': 'Datos de las personas',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_person_data', models.OneToOneField(db_column='id_person_data', on_delete=django.db.models.deletion.CASCADE, related_name='responsible_data', to='clientData.personmodel')),
            ],
            options={
                'verbose_name': 'Datos del responsable tecnico',
                'verbose_name_plural': 'Datos de los responsables tecnicos',
            },
        ),
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_house_data', models.ForeignKey(db_column='id_house_data', on_delete=django.db.models.deletion.CASCADE, related_name='house_x_person_data', to='clientData.houseclientmodel')),
                ('id_person_data', models.OneToOneField(db_column='id_person_data', on_delete=django.db.models.deletion.CASCADE, related_name='person_data', to='clientData.personmodel')),
            ],
            options={
                'verbose_name': 'Datos del Propietario',
                'verbose_name_plural': 'Datos de los propietarios',
            },
        ),
        migrations.AddField(
            model_name='houseclientmodel',
            name='id_municipal_account_data',
            field=models.OneToOneField(db_column='id_municipal_account_data', on_delete=django.db.models.deletion.CASCADE, related_name='municipal_account_data', to='clientData.municipalaccountmodel'),
        ),
        migrations.AddField(
            model_name='houseclientmodel',
            name='id_responsible_data',
            field=models.OneToOneField(db_column='id_responsible_data', on_delete=django.db.models.deletion.CASCADE, related_name='responsible_data', to='clientData.responsiblemodel'),
        ),
    ]
