# Generated by Django 4.0.4 on 2023-02-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownermodel',
            name='id_house_data',
            field=models.ForeignKey(db_column='id_house_data', on_delete=django.db.models.deletion.CASCADE, related_name='house_x_owner_data', to='clientData.houseclientmodel'),
        ),
    ]
