# Generated by Django 4.0.4 on 2023-02-25 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successfull_job', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('progress', models.CharField(choices=[('inp', 'En progreso'), ('fin', 'Finalizado'), ('rec', 'Rectificación'), ('anu', 'Anulado')], max_length=25)),
                ('record', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_house', models.ForeignKey(db_column='id_general_procedure', on_delete=django.db.models.deletion.CASCADE, related_name='house_clients', to='clientData.houseclientmodel')),
            ],
        ),
    ]
