# Generated by Django 4.0.4 on 2022-05-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Número del Identidad')),
                ('type_identification_document', models.CharField(choices=[('Cedula', 'Cedula'), ('Pasaporte', 'Pasaporte')], default='Cedula', max_length=10, verbose_name='Tipo de Identidad')),
                ('fisrt_name', models.CharField(max_length=20, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=20, verbose_name='Segundo nombre')),
                ('father_surname', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('mother_surname', models.CharField(blank=True, max_length=20, verbose_name='Apellido Materno')),
                ('country', models.CharField(blank=True, default='Ecuador', max_length=50, verbose_name='Pais')),
                ('town', models.CharField(blank=True, default='Guayaquil', max_length=50, verbose_name='Ciudad')),
                ('parish', models.CharField(blank=True, max_length=100, verbose_name='Parroquia')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Ciudadela/Coorperativa/Barrio')),
                ('main_road_name', models.CharField(max_length=100, verbose_name='Calle principal')),
                ('cross_road_name', models.CharField(blank=True, max_length=100, verbose_name='Calle transversal')),
                ('mail', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono convensional')),
                ('mobile', models.CharField(blank=True, max_length=10, verbose_name='Celular')),
                ('gender', models.CharField(blank=True, choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('UNDEFINED', 'UNDEFINED')], max_length=10, verbose_name='Genero')),
                ('marital_status', models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Unión libre', 'Unión libre'), ('Separado/a', 'Separado/a')], max_length=15, verbose_name='Estado civil')),
                ('level_of_instruction', models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('3er nivel', '3er nivel'), ('4to nivel', '4to nivel')], max_length=25, verbose_name='Nivel de Instrucción')),
                ('occupation', models.CharField(blank=True, max_length=50, verbose_name='Ocupación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(default='Guayas', on_delete=django.db.models.deletion.CASCADE, to='usersD.provincelist', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
